### ISSUE TITLE
Is TeXmacs support ibus when input Chinese?

### ISSUE THREAD

**Issue by zhcosin** [texmacs/texmacs#24]
My TeXmacs 1.99.5 on debian 9 can not input Chinese while the Chinese input method is active, but it works fine when show Chinese contents copied from Firefox, and I use RIME input method which based ibus, so I guess this may because TeXmacs don't support ibus when input Chinese, Is it true?

**Comment by zhcosin** [comment]
When TeXmacs start, the following error message shown:

> QIconvCodec::convertFromUnicode: using Latin-1 for conversion, iconv_open failed
QIconvCodec::convertToUnicode: using Latin-1 for conversion, iconv_open failed
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
TeXmacs] With linked TrueType support

**Comment by slowphil** [comment]
Where did you get TeXmacs 1.99.5  for Debian 9 from? If you installed the static binary from texmacs.org website, ibus doen't work, it's a known issue with this static package. 
In that case your issue should be solved by using the up-to-date .deb for texmacs in Debian 9 you'll find at this place: https://software.opensuse.org/download.html?project=home:slowphil:texmacs-devel&package=texmacs (Be sure to remove the static binary before installing the .deb !).

Last word: This tracker is not the official one; it is not monitored by a lot of people... I saw your report just by chance. I would advise you to use the user's mailing list to get help working around such issues, and, if needed, the official tracker at https://savannah.gnu.org/bugs/?group=texmacs.

**Comment by zhcosin** [comment]
Very very thanks, it work fine by your method, enjoy my texmacs....
